# Generated by Django 3.1 on 2020-08-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_orderd',
        ),
    ]
