# Generated by Django 3.1 on 2020-09-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200924_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer1',
        ),
    ]
