# Generated by Django 3.1 on 2020-09-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
