# Generated by Django 3.1 on 2020-09-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
